











#spring:
#  data:
#    cassandra:
#      contact-points: localhost
#      port: 9042
#      keyspace-name: bookDB
#      local-datacenter: datacenter1
#      #username: cassandra
#      #password: cassandra
#      #schema-act: create_if_not_exists